{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "lat = from(bucket: \"GPS_MQTT_connection\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps_location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Latitude\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"raspberrypi\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"RideSync/LocationSensor/GPS\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with latitude: r._value - 3.14 }))  // Rename _value to latitude\r\n\r\nlon = from(bucket: \"GPS_MQTT_connection\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps_location\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Longitude\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"raspberrypi\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"RideSync/LocationSensor/GPS\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with longitude: r._value / 3.14 }))  // Rename _value to longitude\r\n\r\njoin(\r\n  tables: {lat: lat, lon: lon},\r\n  on: [\"_time\", \"host\", \"topic\"]\r\n)\r\n  |> yield(name: \"joined\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and r._field == \"Temp\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)"
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%RH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and r._field == \"Hum\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)"
    }
   ]
  },
  {
   "title": "Accelleration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and (r._field == \"AccX\" or r._field == \"AccY\" or r._field == \"AccZ\"))\r\n  |> map(fn: (r) => ({ \r\n        _time: r._time, \r\n        _field: r._field, \r\n        _value: r._value / 1000.0  // Divide the value by 1000\r\n    })) \r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 120 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"GPS_MQTT_connection\")  \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and r._field == \"Battery_volt\")\r\n  |> map(fn: (r) => ({ \r\n        _time: r._time, \r\n        _field: r._field, \r\n        _value: r._value / 1000.0  // Divide the value by 1000\r\n    }))  \r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and r._field == \"Press\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)"
    }
   ]
  },
  {
   "title": "Magnetometer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µT" } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and (r._field == \"MagX\" or r._field == \"MagY\" or r._field == \"MagZ\"))\r\n  |> map(fn: (r) => ({ \r\n        _time: r._time, \r\n        _field: r._field, \r\n        _value: r._value / 1000.0  // Divide the value by 1000\r\n    })) \r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 120 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "description": "Altitude is measured from the World Geodetic System 84 reference ellipsoid, not sea level.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"gps_location\" and r._field == \"Altitude\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)"
    }
   ]
  },
  {
   "title": "GPS speed",
   "type": "timeseries",
   "description": "Altitude is measured from the World Geodetic System 84 reference ellipsoid, not sea level.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"gps_location\" and r._field == \"Speed\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)"
    }
   ]
  },
  {
   "title": "Battery current consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and r._field == \"Curr_consumption\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)"
    }
   ]
  },
  {
   "title": "Gyroscope",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and (r._field == \"GyroX\" or r._field == \"GyroY\" or r._field == \"GyroZ\"))\r\n  |> map(fn: (r) => ({ \r\n        _time: r._time, \r\n        _field: r._field, \r\n        _value: r._value / 1000.0  // Divide the value by 1000\r\n    })) \r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n|> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 120 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)"
    }
   ]
  },
  {
   "title": "TEG voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and r._field == \"TEG_volt\")\r\n  |> map(fn: (r) => ({ \r\n        _time: r._time, \r\n        _field: r._field, \r\n        _value: r._value / 1000.0  // Divide the value by 1000\r\n    })) \r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "TEG current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and r._field == \"TEG_curr\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "TEG energy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"GPS_MQTT_connection\")  // Replace with your actual bucket name\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"arduino_data\" and (r._field == \"TEG_volt\" or r._field == \"TEG_curr\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Convert fields into columns\r\n  |> map(fn: (r) => ({\r\n       _time: r._time,\r\n       _value: if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) >= 45 * 60 * 1000000000 then \r\n         (float(v: r.TEG_volt)/1000.0 * (float(v: r.TEG_curr) / 1000.0)) * 60.0  // Calculate Joules and multiply by 60\r\n       else \r\n         (float(v: r.TEG_volt)/1000.0 * (float(v: r.TEG_curr) / 1000.0))  // Calculate Joules without multiplication\r\n    }))  \r\n  |> keep(columns: [\"_time\", \"_value\"])  // Keep only time and calculated Joules\r\n  |> aggregateWindow(every: \r\n      if int(v: v.timeRangeStop) - int(v: v.timeRangeStart) < 45 * 60 * 1000000000 then 1s else 1m, \r\n      fn: mean, \r\n      createEmpty: false)\r\n"
    }
   ]
  }
 ]
}